config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "pages#home"

  resources :meetings, except: [:destroy] do
    member do
      patch :cancel
    end
    resources :requests, only: [:create]
    resources :messages, only: [:create]
    collection do
      get :historique, to: 'meetings#history'
    end
    member do
      patch :mark_as_full
    end
  end

  get 'meetings/:id/messages', to: 'meetings#messages', as: "meeting_message"
  resources :requests do
    member do
      patch :cancel
      patch :accept
      patch :reject
    end
  end

  resources :games, only: [:create]
  get 'conversations', to: 'meetings#conversations', as: "conversations"
  get 'my-meetings', to: 'meetings#my_meetings', as: "my-meetings"

  resources :notifications, only: [:index]

end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :requests, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy

  accepts_nested_attributes_for :game

  enum status: [ :available, :full, :ongoing, :cancelled, :finished ]

  def localized_status
    I18n.t("activerecord.attributes.meeting.statuses.#{status}")
  end

  geocoded_by :place_address
  # after_validation :geocode, if: :will_save_change_to_place_address?
  # before_save :set_coordinates

  validates :title, :game_id, :players_needed_min, :location_type, :date, presence: true

  private
  # def set_coordinates
  #   result = Geocoder.search(place_address)
  #   unless result.blank?
  #     latitude = result.first.coordinates[0]
  #     longitude = result.first.coordinates[1]
  #   end
  # end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  before_action :set_params, only: %i[show edit update cancel mark_as_full messages]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    Meeting.where.not(status: :finished).each do |meeting|
      if meeting.date <= Date.today - 1
        meeting.finished!
        meeting.save!
      end
    end

    @meetings = Meeting.where.not(status: :cancelled).where.not(status: :finished).where.not(user_id: current_user)

    # Check if location filter is present
    if params[:lat].present? && params[:lng].present? && params[:radius].present?
      close_meetings = Meeting.near([params[:lat], params[:lng]], params[:radius])
      @meetings &= close_meetings
    end

    # Check if date filter is present
    if params[:daterange].present?
      start_date = params[:daterange].split(" to ")[0]
      params[:daterange].split(" to ")[1].nil? ? end_date = start_date : end_date = params[:daterange].split(" to ")[1]
      timely_meetings = Meeting.where(date: start_date..end_date)
      @meetings &= timely_meetings
    end

    # Check if keyword filter is present
    if params[:search].present?
      params[:search].split(' ').each do |term|
        keyword_meetings = Meeting.joins(:game).where(
          "title ILIKE :term OR games.name ILIKE :term OR games.category ILIKE :term OR location_type ILIKE :term OR place_name ILIKE :term OR place_address ILIKE :term OR lower(tags::text) LIKE lower(:term)",
          term: "%#{term}%"
        )
        @meetings &= keyword_meetings
      end
    end
    @now = Time.now
    @sorted_meetings = @meetings.to_a.sort_by { |meeting| (Time.parse(meeting.date.to_s) - @now) }

    @request = Request.new
    # raise

    # @cities = JSON.parse(File.read(Rails.root.join('./cities.json')))['cities']
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @cities }
    # end
  end

  def my_meetings
    @now = Time.now
    @my_meetings = current_user.meetings.where.not(status: :cancelled)
    # @my_meetings.each do |meeting|
    #   if meeting.date < Date.today
    #     meeting.finished!
    #     meeting.save!
    #   end
    # end
    @my_meetings = current_user.meetings.where.not(status: :finished)
    @my_sorted_meetings = @my_meetings.to_a.sort_by { |meeting| (Time.parse(meeting.date.to_s) - @now) }
  end

  def show
    @request = Request.new
    @user = current_user
    if @user
      @user_request = Request.find_by(meeting_id: @meeting.id, user_id: @user.id)
    else
      @user_request = nil
    end
  end

  def new
    @games = Game.all
    @meeting = Meeting.new
  end

  def create
    @games = Game.all
    @meeting = Meeting.new(meeting_params)
    if @games.pluck(:id).include?(params[:meeting][:game_id].to_i)
      @meeting.game_id = params[:meeting][:game_id]
    else
      @new_game = Game.create(name: params[:meeting][:game_id])
      @new_game.save!
      @meeting.game_id = @new_game.id
    end
    @meeting.players_needed_max = @meeting.players_needed_min if @meeting.players_needed_max.blank?
    @meeting.user = current_user
    @meeting.available!
    # raise
    if @meeting.save!
      # raise
      redirect_to requests_path
      flash.notice = "Rencontre pour #{@meeting.game.name} créée avec succès"
    else
      # raise
      render :new, status: :unprocessable_entity
      flash.notice = "Erreur lors de la création de la rencontre"
    end
  end

  def conversations
    @planner_conversations = Meeting.where(user: current_user)
    @participant_conversations = Meeting.joins(:requests).where(requests: { user_id: current_user })
  end

  def messages
    @message = Message.new
  end

  def edit
  end

  def update
    if @meeting.update!(meeting_params)
      redirect_to meeting_path(@meeting)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def mark_as_full
    if @meeting.full?
      @meeting.available!
      redirect_to requests_path if @meeting.save!
    elsif @meeting.available?
      @meeting.full!
      redirect_to requests_path if @meeting.save!
    else
      render :requests_path, status: :unprocessable_entity
    end
  end

  def history
    @finished_meetings = Meeting.where(status: Meeting.statuses[:finished])
    @other_requests = Request.where(meeting_id: @meetings)
  end

  def cancel
    if @meeting.user == current_user
      if @meeting.cancelled!
        render json: {
          message: "Votre rencontre à été supprimée.",
          title: @meeting.localized_status,
          redirect_url: requests_path
          }, status: :ok
      else
        render json: {
          message: "Quelque chose s'est mal passé 😥",
          title: "Oups.."
          }, status: :unprocessable_entity
      end
    else
      render json: {
        message: "Vous n'êtes pas autorisé à annuler cette rencontre.",
        title: "Accès refusé"
      }, status: :forbidden
    end
  end

  private

  def set_params
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:title, :description, :players_needed_min, :players_needed_max, :location_type,
                                    :place_name, :place_address, :latitude, :longitude, :status, :level, :date,
                                    :game_id, :tags)
  end

end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_filter_form.html.erb
    <button class="btn btn-primary mt-2 p-2 col-6 mx-auto rounded-pill"
            data-action="click->show-filters#display"
            data-show-filters-target="filtersButton">
            FILTRE V2
    </button>
    <div class="filter-form d-none " data-show-filters-target="showFilters">
      <%= form_with url: meetings_path, method: :get, local: true do %>
        <div class="col-md-5 my-2">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Jeu, Catégorie, Adresse, Lieu, Tags etc." %>
        </div>
        <div class="col-md-5 my-2">
          <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Jeu, Catégorie, Adresse, Lieu, Tags etc." %>
        </div>
        <div class="col-md-2">
          <%= submit_tag "Appliquer les filtres", class: "btn btn-success rounded-pill" %>
        </div>
      <% end %>
    </div>

app/views/meetings/conversations.html.erb
<div class="container">





  <div class="accordion" id="accordionConvo">
    <div class="accordion-item">
      <div class="d-flex">
        <h2 class="accordion-header flex-fill mr-4" id="headingOne">
          <button class="accordion-button rounded-3" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Organisateur
          </button>
        </h2>
        <h2 class="accordion-header flex-fill ml-4" id="headingTwo">
          <button class="accordion-button rounded-3 collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Participant
          </button>
        </h2>
      </div>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionConvo">
        <div class="accordion-body">
          <div class="messages-list">
            <% @planner_conversations.each do |meeting| %>
              <% unless meeting.messages.blank? %>
                <div class="chat-preview shadow my-2 p-1">
                  <%= link_to(meeting_messages_path(meeting)) do %>
                    <p class="px-1"><strong><%= meeting.title %></strong></p>
                    <p class="px-1 mb-1"><strong><%= meeting.game.name %></strong> - le <%= meeting.date.strftime("%d/%m/%y à %H:%M") %></p>
                    <%# <p><i><%= meeting.place_name meeting.place_address </i></p> %>
                    <% unless meeting.messages.last.nil? %></p>
                      <p class="message-preview p-1"><%= meeting.messages.last.user.username %> : <%= meeting.messages.last.content %>, <i> le <%= meeting.messages.last.created_at.strftime("%d/%m/%g à %H:%M") %></i></p>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="accordion-item">

      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionConvo">
        <div class="accordion-body">
          <div class="messages-list">
            <% @participant_conversations.each do |meeting| %>
              <% unless meeting.messages.blank? %>
                <div class="chat-preview shadow my-2 p-2">
                  <%= link_to(meeting_messages_path(meeting)) do %>
                    <p><strong><%= meeting.title %></strong></p>
                    <p><strong><%= meeting.game.name %></strong> - le <%= meeting.date.strftime("%d/%m/%y à %H:%M") %></p>
                    <%# <p><i><%= meeting.place_name meeting.place_address </i></p> %>
                    <% unless meeting.messages.last.nil? %></p>
                      <p class="message-preview px-2"><%= meeting.messages.last.user.username %> : <%= meeting.messages.last.content %>, <i> le <%= meeting.messages.last.created_at.strftime("%d/%m/%g à %H:%M") %></i></p>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/meetings/index.html.erb
<div class="container">
  <h1 class="text-center">Trouve des potes pour jouer près de chez toi !</h1>

  <div class="row text-center p-2 mx-auto" data-controller="show-filters location-filter">
    <div class="d-grid gap-2 col-6 mx-auto">
      <button class="btn btn-primary btn-sm mt-3 p-2 rounded-pill mx-auto"
              data-action="click->show-filters#display"
              data-show-filters-target="filtersButton">
              Filtrer les résultats +
      </button>
      <%= link_to "Réinitialiser", meetings_path, class:"small-link text-decoration-none mb-3" %>
    </div>

    <div class="row mx-auto">
      <div class="filter-form d-none p-2 mb-4 mx-auto" data-show-filters-target="showFilters">
        <%= form_with url: meetings_path, method: :get, local: true do %>
          <div class="container">
            <div class="row align-items-center justify-content-center">
              <div class="my-2">
                <%= search_field_tag :location, params[:location], class: "form-control d-none", id: "aroundMe", placeholder: "Localisation", data: { location_filter_target: "aroundMeField"} %>
                <%= search_field_tag :city, params[:city], class: "form-control", id: "cityInp", placeholder: "Recherche ta ville", data: { location_filter_target: "cityInput", action: "keyup->location-filter#displayCities"} %>
                <ul data-location-filter-target="results" class="no-bullet"></ul>
                <div class="form-switch my-2 p-0">
                  <div class="d-flex justify-content-left p-0">
                    <label class="form-check-label text-muted" for="flexSwitchCheckDefault">Rechercher par géolocalisation</label>
                    <input class="form-check-input margin-left" type="checkbox" id="flexSwitchCheckDefault" data-location-filter-target="toggler" data-action="click->location-filter#revealField">
                  </div>
                </div>
                <div class="d-flex">
                  <label for="radius" class="form-label text-muted">Rayon</label>
                  <input id="radius" class="form-range margin-left-and-right" data-location-filter-target="radius"  data-action="change->location-filter#updateRadius" type="range" value="10" min="1" max="200" oninput="this.nextElementSibling.value = this.value">
                  <output ml-4>10</output>km<br>
                </div>
              </div>
              <%# hidden filter form fields %>
              <div class="my-2 d-none" type="button">
                <%= text_field_tag :lat, params[:lat], class: "form-control", placeholder: "lat", data: { location_filter_target: "fieldLat", location_filter_target: "fieldLat"} %>
              </div>
              <div class="my-2 d-none" type="button">
                <%= text_field_tag :lng, params[:lng], class: "form-control", placeholder: "lng", data: { location_filter_target: "fieldLng", location_filter_target: "fieldLng"} %>
              </div>
              <div class="col-md-5 my-2 d-none" type="button">
                <%= text_field_tag :radius, params[:radius], class: "form-control", placeholder: "radius", data: { location_filter_target: "fieldRadius"} %>
              </div>
              <%# /hidden %>
              <div class="my-2">
                <%= search_field_tag :daterange, params[:daterange], class: "form-control", placeholder: "Choisis des dates", data: { controller: "date-filter"} %>
              </div>
              <div class="my-2">
                <%= search_field_tag :search, params[:search], class: "form-control", placeholder: "Recherche par mots-clés : contrée, société ..." %>
              </div>
              <div class="">
                <%= submit_tag "Valider", class: "btn btn-success rounded-pill" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="meetings-container">
      <% if @sorted_meetings.blank? %>
        <p>Désolé, ta recherche n'a retourné aucun résultat</p>
        <%= link_to "Réinitialiser la recherche", meetings_path %>
      <% else %>

        <% @sorted_meetings.each do |meeting| %>

          <div class="meeting-card shadow rounded-4 row mb-3 shadow" style="overflow: hidden;">
            <% if meeting.user != current_user %>
              <%= link_to(meeting_path(meeting), class: "show-link") do %>

                <div class="row meeting-card-top">
                  <% unless meeting.user.profile_picture.attached? %>
                    <%= image_tag("profil.png", class: "profile-pic") %>
                  <% else %>
                    <%= cl_image_tag(meeting.user.profile_picture.key, class: "profile-pic") %>
                  <% end %>

                  <div class="col-3 p-2 <%= meeting_status_class(meeting.status) %> d-flex flex-column justify-content-center align-items-center justify-space-around">
                    <p class="fs-1 fw-bold"><%= meeting.date.strftime("%d") %></p>
                    <p><%= meeting.date.strftime("%B") %></p>
                    <p><%= meeting.date.strftime("%H:%M") %></p>
                  </div>

                  <div class="col-9 p-2" style="height: 100%;">
                    <div>
                      <div class="col-9 mx-auto">
                        <h3><%= meeting.game.name %></h3>
                      </div>
                      <h6><%= meeting.title %></h6>
                      <div class="d-none">
                        <p>
                          Joueurs :
                          <%= meeting.players_needed_min %>
                            <% if !meeting.players_needed_max.blank? %>
                            à
                            <%= meeting.players_needed_max %>
                            <% end %>
                        </p>
                      </div>
                      <p class="place-info"> <%= meeting.place_name %>, <%= meeting.place_address %> </p>
                    </div>
                  </div>
                </div>
                <div class="row meeting-card-bottom <%= meeting.full? ? "bg-danger" : "bg-warning" %>">
                  <div class="text-light d-flex justify-content-center align-items-center p-1">
                    <% if meeting.full? %>
                      <p>
                        <%= meeting.localized_status %>
                      </p>
                    <% else %>
                      <p>Recherche
                        <strong>
                          <%= meeting.players_needed_min %>
                        </strong>
                        joueurs.ses
                      </p>
                    <% end %>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>

        <% end %>
      <% end %>
    </div>

  </div>
  <%= render "shared/fixed_new_button" %>
</div>

app/views/meetings/messages.html.erb
  <div class="message-card row mb-3">

    <%= link_to(meeting_path(@meeting), class: "show-link") do %>

      <div class="row message-card-top">

        <div class="col-3 <%= meeting_status_class(@meeting.status) %> d-flex flex-column justify-content-center align-items-center">
          <%# code %>
          <h1><%= @meeting.date.strftime("%d") %></h1>
          <p><%= @meeting.date.strftime("%B") %></p>
          <p><%= @meeting.date.strftime("%H:%M") %></p>
        </div>

        <div class="col-9 p-2 bg-light" style="height: 100%;">
          <div class="position relative">
            <button type="button" class="btn-close position-absolute top-0 end-0 m-2" aria-label="Close" onclick="window.location.href='/conversations'"></button>
            <h1><%= @meeting.game.name %></h1>
            <p><%= @meeting.title %></p>
            <p class="d-none">Niveau : <%= @meeting.level %></p>
            <p><%= @meeting.place_address %></p>
          </div>
        </div>
      </div>

    <div class="row message-card-bottom bg-warning">
      <div class="text-light d-flex justify-content-center align-items-center">
        <p>Recherche <strong><%= @meeting.players_needed_min %> </strong>joueurs.ses</p>
      </div>
    </div>

    <% end %>
  </div>

  <div class="container chat text-dark">
    <%= link_to(conversations_path) do %>
      <i class="fa-solid fa-left-long"></i>
    <% end %>

  <%= turbo_stream_from "meeting_#{@meeting.id}_messages" %>

  <div id="messages" class="messages">
    <% @meeting.messages.each do |message| %>
      <%= render "messages/message", message: message, user: current_user %>
    <% end %>
  </div>

  <%= simple_form_for [@meeting, @message],
    html: {class: "d-flex",
    data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }} do |f|
  %>
    <%# <% other_user = current_user == @meeting.user ? @meeting.user : @meeting.restaurant.user %>
    <%= f.input :content,
      label: false,
      placeholder: "Message au groupe", # #{other_user.username}",
      wrapper_html: {class: "flex-grow-1"},
      input_html: {class: "form-control message-input"}
    %>
    <%= f.submit "Envoyer", class: "btn btn-success mb-3 send-button" %>
  <% end %>
</div>

app/views/meetings/my_meetings.html.erb
<div class="container">
  <div class="row text-center px-3" data-controller="show-filters">
    <h1 class="my-4">Mes annonces</h1>

    <div class="meetings-container p-2">

      <% @my_sorted_meetings.each do |meeting| %>

        <div class="meeting-card shadow rounded-4 row mb-3" style="overflow: hidden;">
          <%= link_to(meeting_path(meeting), class: "show-link") do %>

            <div class="row meeting-card-top">
              <% unless meeting.user.profile_picture.attached? %>
                <%= image_tag("profil.png", class: "profile-pic") %>
              <% else %>
                <%= cl_image_tag(meeting.user.profile_picture.key, class: "profile-pic") %>
              <% end %>

              <div class="col-3 p-2 <%= meeting_status_class(meeting.status) %> d-flex flex-column justify-content-center align-items-center">
                <p class="fs-1 fw-bold"><%= meeting.date.strftime("%d") %></p>
                <p><%= meeting.date.strftime("%B") %></p>
                <p><%= meeting.date.strftime("%H:%M") %></p>
            </div>

            <div class="col-9 p-2" style="height: 100%;">
              <div>
                <div class="col-9 mx-auto">
                  <h3><%= meeting.game.name %></h3>
                </div>
                <h6><%= meeting.title %></h6>
                <div class="d-none">
                  <p>
                    Joueurs :
                    <%= meeting.players_needed_min %>
                      <% if !meeting.players_needed_max.blank? %>
                      à
                      <%= meeting.players_needed_max %>
                      <% end %>
                  </p>
                </div>
                <p class="place-info"> <%= meeting.place_name %>, <%= meeting.place_address %> </p>
              </div>
            </div>
          </div>
          <div class="row meeting-card-bottom <%= meeting.full? ? "bg-danger" : "bg-warning" %>">
            <div class="text-light d-flex justify-content-center align-items-center p-1">
              <% if meeting.full? %>
                <p>
                  <%= meeting.localized_status %>
                </p>
              <% else %>
                <p>Recherche
                  <strong>
                    <%= meeting.players_needed_min %>
                  </strong>
                  joueurs.ses
                </p>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    </div>
    <div class="row col-6 m-auto pt-3 gap-2">
      <%= link_to "Retour", :back, class: "btn btn-secondary" %>
      <%= link_to "Liste des jeux", meetings_path, class: "btn btn-secondary" %>
    </div>
  </div>

  <%= link_to new_meeting_path, class: "fixed-button" do %>
    <i class="fa-solid fa-plus create-icon"></i>
  <% end %>
</div>

app/views/meetings/show.html.erb
<div class="container p-3 mt-3">
  <div class="row justify-content-center">
    <div class="col-lg-6 shadow rounded-3 mb-3 show-card shadow" data-controller="show-meetings-interest">
      <div class="user-div d-flex align-items-center">
        <% unless @meeting.user.profile_picture.attached? %>
          <%= image_tag("profil.png", class: "img-fluid rounded-circle", style: 'height: 40px; width: 40px;') %>
        <% else %>
          <%= cl_image_tag(@meeting.user.profile_picture.key, class: "img-fluid rounded-circle", style: 'height: 40px; width: 40px;') %>
        <% end %>
        <p class="text-center m-0 fst-italic"> par <%= @meeting.user.username %></p>
      <%= link_to :back do %>
          <button class="btn-close close-button" aria-label="Close"></button>
      <% end %>
      </div>

      <h2 class="pt-3 text-center"><%= @meeting.title %></h2>

      <% if @meeting.user != current_user %>
        <% if @user_request.nil? %>
        <div class="row justify-content-center mb-4">


          <button class="btn btn-primary mt-2 p-2 col-6 rounded-pill"
                  data-action="click->show-meetings-interest#display"
                  data-show-meetings-interest-target="interested">
                  Je suis intéressé.e
          </button>

          <div class="container my-5 d-none" data-show-meetings-interest-target="friends">
            <div class="row text-center">
              <%= simple_form_for @request, url: meeting_requests_path(@meeting), method: :post do |f| %>

                <%= f.input :number_of_friends,
                            label: "Tu veux participer avec des amis? Précise le à l'organisateur.rice",
                            # collection: (0..@meeting.players_needed_max - 1).map { |friends| [friends == 0 ? "Je suis seul.e" : friends == 1 ? "1 ami" : "#{friends} amis", friends] },
                            collection: (0..@meeting.players_needed_max),
                            prompt: "Sélectionnez le nombre d'amis",
                            input_html: { class: "form-control col-3", data: { price_calculator_target: "numberOfFriends" } } %>
                <div class="text-center">
                  <%= f.submit 'Envoyer la demande', class: "btn btn-default btn-primary rounded-pill" %>
                </div>

              <% end %>
            </div>
          </div>
        </div>

        <% elsif @user_request.accepted? || @user_request.interested? %>
          <div class="row justify-content-center d-flex">
            <%= link_to "Accéder à la conversation", meeting_messages_path(@meeting), class: "btn btn-primary mt-1 mb-3 p-2 col-6 rounded-pill" %>
          </div>
          <div class="row justify-content-center d-flex">
            <%= link_to 'Annuler ma participation', request_path(@user_request), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous certain de vouloir annuler cette demande?" }, class: "btn btn-danger mt-1 mb-3 p-2 col-6 rounded-pill" %>
          </div>

        <% elsif @user_request.rejected? %>
          <div class="rejected-request bg-danger text-center mb-3">
            <p>Votre demande a été refusée</p>
          </div>
        <% end %>

        <% elsif @meeting.user == current_user %>
        <div class="row justify-content-center d-flex">
          <%= link_to "Accéder à la conversation", meeting_messages_path(@meeting), class: "btn btn-primary mt-2 mb-1 p-2 col-6 rounded-pill" %>
        </div>
        <div class="row justify-content-center d-flex">
          <%= link_to "Modifier mon annonce", edit_meeting_path(@meeting), class: "btn btn-primary mt-1 mb-3 p-2 col-6 rounded-pill" %>
        </div>
      <% end %>

      <div class="d-flex justify-content-between border-top pt-3">
        <p><strong>Jeu</strong></p>
        <span><%= @meeting.game.name %></span>
      </div>

      <div class="d-flex justify-content-between">
        <p><strong>Nombre de joueurs recherchés</strong></p>
        <span><%= @meeting.players_needed_min %>
          <% unless @meeting.players_needed_max == @meeting.players_needed_min || @meeting.players_needed_max.blank? %>
            à <%= @meeting.players_needed_max %></span>
          <% end %>
      </div>

      <div class="d-flex justify-content-between">
        <p><strong>Niveau</strong></p>
        <span><%= @meeting.level %></span>
      </div>

      <div class="d-flex justify-content-between">
        <p><strong>Catégorie</strong></p>
        <span><%= @meeting.game.category.capitalize unless @meeting.game.category.blank?  %>
      </div>


      <div class="d-flex justify-content-between">
        <p><strong>Localisation</strong></p>
        <div class="row pb-2">
          <span class="text-end"><%= @meeting.location_type %></span>
          <span class="text-end"><%= @meeting.place_name %></span>
          <span class="text-end"><%= @meeting.place_address %></span>
        </div>
      </div>

      <div class="d-flex justify-content-between pb-2">
        <p><strong>Date</strong></p>
        <span>le <i><%= @meeting.date.strftime("%d/%m/%y à %H:%M") %></i></span>
      </div>

      <% if !@meeting.description.blank? %>
        <div>
          <p><strong>Description</strong></p>
          <p class="bg-light rounded-3 p-3 text-dark"><%= @meeting.description %></p>
        </div>
      <% end %>

    <div class="participants">
      <% if @meeting.user == current_user %>
        <p>Participants</p>
            <div class="d-flex gap-1 flex-column">
              <div class="d-flex align-items-center bg-secondary-subtle p-1 rounded-4 shadow">
                  <p class="mb-0"><%= @meeting.user.username %> (moi)</p>
              </div>
              <% @meeting.requests.each do |request| %>
                <% if !request.rejected? %>
                  <div class="d-flex justify-content-between align-items-center rounded-4 p-1 shadow <%= request.status == "interested" ? "bg-danger-subtle" : "bg-success-subtle" %>">
                    <%= link_to request_path(request), class: "text-decoration-none text-black" do %>
                      <p class="mb-0">
                        <%= request.user.username %>
                        <% if request.number_of_friends == 0 %>
                          seul(e)
                        <% elsif request.number_of_friends == 1 %>
                          + 1 ami(e)
                        <% else %>
                          + <%= request.number_of_friends %> ami(e)s
                        <% end %>
                      </p>
                    <% end %>
                    <div>
                      <%= link_to accept_request_path(request), class: "text-decoration-none text-black", data: { turbo_method: :patch } do %>
                        <% if request.interested? %>
                          <i class="fa-regular fa-circle-check px-2"></i>
                        <% end %>
                      <% end %>
                      <%= link_to reject_request_path(request), class: "text-decoration-none text-black", data: { turbo_method: :patch, turbo_confirm: "Es-tu certain d'annuler cette demande?" } do %>
                        <i class="fa-solid fa-xmark"></i>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>


        <%= link_to cancel_meeting_path(@meeting), data: { turbo_method: :patch, turbo_confirm: "Es-tu certain d'annuler cette rencontre?", controller: "cancel-meeting-alert", action: "click->cancel-meeting-alert#alert"} do %>
          <div class="row justify-content-center d-flex">
            <button id="meeting-<%= @meeting.id %>" class="btn btn-danger mt-2 p-2 col-6 rounded-pill">Annuler la rencontre</button>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>