config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "pages#home"

  resources :meetings, except: [:destroy] do
    member do
      patch :cancel
    end
    resources :requests, only: [:create]
    resources :messages, only: [:create]
    collection do
      get :historique, to: 'meetings#history'
    end
    member do
      patch :mark_as_full
    end
  end

  get 'meetings/:id/messages', to: 'meetings#messages', as: "meeting_message"
  resources :requests do
    member do
      patch :cancel
      patch :accept
      patch :reject
    end
  end

  resources :games, only: [:create]
  get 'conversations', to: 'meetings#conversations', as: "conversations"
  get 'my-meetings', to: 'meetings#my_meetings', as: "my-meetings"

  resources :notifications, only: [:index]

end

app/views/shared/_fixed_new_button.html.erb
<%= link_to new_meeting_path, class: "fixed-button" do %>
  <i class="fa-solid fa-plus create-icon"></i>
<% end %>

app/views/shared/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_meeting_form.html.erb
<div
      class="col-lg-12 px-5 shadow py-3"
      data-controller="game-select poi-autocomplete players-max step-by-step"
      data-poi-autocomplete-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      <a href="/meetings" class="btn-close close-button-meeting-new" aria-label="Close"></a>

      <%= simple_form_for @meeting do |f| %>

        <div class="game-part" data-step-by-step-target="gameInfo">
          <%= f.input :game_id,
                      label: "Commençons par le jeu",
                      input_html: {id: "input-tags", placeholder: "Contrée, 7 Wonders", autocomplete: "off"},
                      collection: @games
                      %>
          <%= f.input :players_needed_min,
                      placeholder: "1, 2, 3...",
                      label: "De combien de joueurs as-tu besoin (min)?" %>
          <%# <% if @meeting.errors.include?(:players_needed_min) %>
          <div class="form-check form-switch mb-4">
            <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" data-action="click->players-max#reveal">
            <label class="form-check-label text-muted" for="flexSwitchCheckDefault">Donner une fourchette, ex: entre 2 et 5 participants</label>
          </div>
          <%= f.input :players_needed_max,
                      placeholder: "1, 2, 3...",
                      label: "Et au max ?",
                      wrapper_html: {data: {players_max_target: "field" }, class: "d-none"}
                      %>
          <%= f.input :level,
                      placeholder: "Débutant, confirmé, expert ?",
                      collection: ["Débutant", "Normal", "Expert", "Pas de restriction"],
                      label: "Quel niveau souhaites-tu donner à ta rencontre ?"%>

          <div class="prev-and-next d-flex justify-content-end">
            <button class="btn btn-primary btn-sm" type="button" data-action="click->step-by-step#goToMeetingInfo">
              <i class="fa-solid fa-arrow-right"></i>
            </button>
          </div>
        </div>

        <div class="meeting-part d-none" data-step-by-step-target="meetingInfo">
          <h3 data-action="click->step-by-step#tester"> Précise les modalités du rendez-vous </h3>
          <%= f.input :date,
                      as: :string,
                      label: "A quelle date aura lieu le rendez-vous ?",
                      input_html: { data: { controller: "datetime-selector" } }%>
          <%= f.input :location_type,
                      placeholder: "Café, Bar, Parc, A domicile ...",
                      label: "Dans quel type de lieu veux-tu jouer?",
                      collection: ["Parc", "Café / Bar", "A définir", "A domicile"]%>
          <p>Recherche le nom de l'établissement, quartier, ville</p>
          <div data-poi-autocomplete-target="searchBox" class="mb-3"></div>
          <div class="d-none" data-poi-autocomplete-target="divToDisplay">
            <%= f.input :place_name,
                        label: "Etablissement, quartier, arrondissement",
                        input_html: { data: { poi_autocomplete_target: "name" }, class:"secondary-form"} %>
            <%= f.input :place_address,
                        label: "Adresse",
                        input_html: { data: { poi_autocomplete_target: "address" }, class:"secondary-form"} %>
          </div>
           <div class="d-none">
             <%= f.input :latitude,
                        label: "Latitude",
                        input_html: { data: { poi_autocomplete_target: "latitude" }, class:"secondary-form"} %>
            <%= f.input :longitude,
                        label: "Longitude",
                        input_html: { data: { poi_autocomplete_target: "longitude" }, class:"secondary-form"} %>
          </div>

          <div class="prev-and-next d-flex justify-content-between">
            <button class="btn btn-primary btn-sm" type="button" data-action="click->step-by-step#goToGameInfo">
              <i class="fa-solid fa-arrow-left"></i>
            </button>
            <button class="btn btn-primary btn-sm" type="button" data-action="click->step-by-step#goToTitleAndDesc">
              <i class="fa-solid fa-arrow-right"></i>
            </button>
          </div>
        </div>
        <div class="title-and-desc-part d-none" data-step-by-step-target="titleAndDesc">
          <h3>Donne un titre à ton annonce</h3>
          <%= f.input :title,
                    placeholder: "Titre de ton annonce",
                    label: "Titre" %>
          <%= f.input :tags,
                      label: "Indique quelques mots-clés pour faciliter la recherche",
                      input_html: {id: "filter-tags", placeholder: "Cartes, stratégie, ambiance", autocomplete: "off"}
                      %>
          <%= f.input :description,
                    placeholder: "(Optionnel) Ajouter une description..."
                    %>
          <div class="prev-and-next d-flex justify-content-start">
            <button class="btn btn-primary btn-sm" type="button" data-action="click->step-by-step#goToMeetingInfo">
              <i class="fa-solid fa-arrow-left"></i>
            </button>
          </div>
          <div class="text-center pt-3">
            <%= f.button :submit, "Soumettre", class: "btn btn-primary " %>
            <%= link_to "Annuler", meetings_path, class: "btn btn-danger text-white" %>
          </div>
        </div>
      <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 align-items-center">
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Trouver un jeu", meetings_path, class: "nav-link text-primary" %>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link"><%= current_user.username %></a>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% unless current_user.profile_picture.attached? %>
                <%= image_tag "profil.png", class: "avatar rounded-circle", alt: "dropdown menu" %>
              <% else %>
                <%= cl_image_tag current_user.profile_picture.key, class: "avatar rounded-circle", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Activités", requests_path, class: "dropdown-item" %>
              <%= link_to "Conversations", conversations_path, class: "dropdown-item" %>
              <%= link_to "Mes annonces", my_meetings_path, class: "dropdown-item" %>
              <%= link_to "Modifier mes informations", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item bg-danger" %>
            </div>
          </li>

          <li class="nav-item">
            <%= link_to notifications_path, class: "nav-link text-primary" do %>
              <i class="fa fa-bell"></i>
            <% end %>
          </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Trouver un jeu", meetings_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Me connecter", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_request_form.html.erb
<%= simple_form_for(@request) do |f| %>
  <%= f.hidden_field :status, value: "En attente de validation" %>
  <%= f.hidden_field :meeting_id, value: @meeting.id %>
  <%= f.input :number_of_friends, label: "Nombre d'ami qui m'accompagne" %>
  <%= f.submit "Je suis interessé.e!" %>
<% end %>