config/routes.rb
Rails.application.routes.draw do
  get 'notifications/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "pages#home"

  resources :meetings, except: [:destroy] do
    member do
      patch :cancel
    end
    resources :requests, only: [:create]
    resources :messages, only: [:create]
    collection do
      get :historique, to: 'meetings#history'
    end
    member do
      patch :mark_as_full
    end
  end

  get 'meetings/:id/messages', to: 'meetings#messages', as: "meeting_message"
  resources :requests do
    member do
      patch :cancel
      patch :accept
      patch :reject
    end
  end

  resources :games, only: [:create]
  get 'conversations', to: 'meetings#conversations', as: "conversations"
  get 'my-meetings', to: 'meetings#my_meetings', as: "my-meetings"

  resources :notifications, only: [:index]

end

app/models/request.rb
class Request < ApplicationRecord
  enum status: { interested: "En attente de validation", accepted: "Validé", rejected: "Annulé" }

  # validates :meeting_id, uniqueness: { scope: :user_id, alert: "Vous avez déjà fait une demande pour cette partie", condidions: -> { where(status: "Annuler") } }

  belongs_to :meeting
  belongs_to :user
  has_many :notifications, as: :notifiable, dependent: :destroy
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

  helper_method :compute_players
  before_action :set_request, except: [:index, :create]


  # CRUD methods
  def index
    @requests = current_user.meetings.joins(:requests)
    @user_meetings = Meeting.where(user_id: current_user).where.not(status: :cancelled).where.not(status: :finished)
    @requested_meetings = Meeting.joins(:requests).where(requests: { user_id: current_user }).where.not(requests: { status: :rejected })
    @user_meetings.each do |meeting|
      if meeting.date < Date.today
        meeting.finished!
        meeting.save!
      end
    end

    current_user.update(viewed_requests_count: 0) if current_user.viewed_requests_count.nil?
    current_user.update(viewed_requests_count: Request.where(meeting: current_user.meetings).count)
  end

  def show
  end

  def create
    @meeting = Meeting.find(params[:meeting_id])
    if Request.where(user_id: current_user.id, meeting_id: @meeting.id).exists? || @meeting.full?
      render json: { error: "You have already requested to join this meeting" }, status: :unprocessable_entity
    else
      @request = Request.new(request_params)
      @request.user = current_user
      @request.meeting = @meeting
      if request_params[:number_of_friends] == ""
        @request.number_of_friends = 0
      end
      @request.interested!
      if @request.save!
        @notification = Notification.new(
          notifiable_type: 'Meeting',
          notifiable_id: @request.meeting.id,
          category: 'pending-request',
          content: "Demande en attente d'approbation pour #{@request.meeting.game.name} le #{@request.meeting.date.strftime('%d/%m/%y')}")
        @notification.unread!
        @notification.save!
        NotifierMailer.with(user: @request.meeting.user, notification: @notification).notification_email.deliver_now
        redirect_to requests_path
      else
        redirect_to meeting_path(@meeting), status: :unprocessable_entity
      end
    end
  end

  def edit
  end

  def update
    if @request.update!(request_params)
      redirect_to requests_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def reject
    @request.status = Request.statuses[:rejected]
    redirect_to requests_path if @request.save!
  end

  def accept
    @request.status = Request.statuses[:accepted]
    @notification = Notification.new(
      notifiable_type: 'Request',
      notifiable_id: @request.id,
      category: 'approved-request',
      content: "Demande acceptée pour #{@request.meeting.game.name} le #{@request.meeting.date.strftime('%d/%m/%y')}")
    @notification.unread!
    @notification.save!
    # raise
    NotifierMailer.with(user: @request.user, notification: @notification).notification_email.deliver_now
    # , url: meeting_path(@request.meeting)
    redirect_to requests_path if @request.save!
  end

  def destroy
    @request.destroy
    redirect_to requests_path, status: :see_other
  end

  def cancel
    @request.rejected!
    redirect_to meetings_path
  end

  # Other methods

  def compute_players(meeting)
    counter = 0
    meeting.requests.where(status: :accepted).each do |e|
      counter += e.number_of_friends
    end
    counter + meeting.requests.where(status: :accepted).count + 1
  end

  private

  def set_request
    @request = Request.find(params[:id])
  end

  def request_params
    params.require(:request).permit(:number_of_friends, :status, :meeting_id)
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/edit.html.erb
<div class="container">
  <%= simple_form_for(@request) do |f| %>
    <%# <%= f.input :status, collection: Request.statuses.except(:accepted).values, selected: @request.status %>
    <%= f.input :number_of_friends, label: "Nous ne sommes plus le même nombre de joueur" %>
    <%= f.submit "Mettre à jour" %>
  <% end %>
</div>

app/views/requests/index.html.erb
<div class="container">
  <h1 class="text-center pb-3">Mon activité</h1>
  <div class="accordion" id="accordionConvo">
    <div class="accordion-item">

      <div class="d-flex">
        <h2 class="accordion-header flex-fill" id="headingOne">
          <button class="accordion-button rounded-3" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Organisateur, <%= @user_meetings.count %>
          </button>
        </h2>
        <h2 class="accordion-header flex-fill ml-4" id="headingTwo">
          <button class="accordion-button rounded-3 collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Participant, <%= @requested_meetings.count %>
          </button>
        </h2>
      </div>

      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionConvo">
        <div class="accordion-body">

          <% @user_meetings.each do |meeting| %>
            <div class="p-1 mt-4 rounded-5">
              <div class="request-card bg-white text-black px-3 rounded-5 shadow">
                <div class="d-flex justify-content-between mb-2">
                  <div class="text-start">
                    <h4 class="mb-0"><%= link_to meeting.game.name, meeting_path(meeting) %></h4>
                    <p class="location-small text-secondary">
                          <i class="fa-solid fa-location-dot"></i>
                          <% if meeting.place_name.blank? %>
                            Aucun lieu défini
                          <% else %>
                            <%= meeting.place_name %>
                          <% end %>
                    </p>
                  </div>

                  <%= link_to mark_as_full_meeting_path(meeting), data: { turbo_method: :patch } do %>
                    <div class="form-check form-switch m-0 d-flex justify-content-end">
                      <label class="form-check-label ps-2 pe-5" for="switch-<%= meeting.id %>"><%= meeting.localized_status %></label>
                      <input class="form-check-input" type="checkbox" role="switch" id="switch-<%= meeting.id %>" <%= "checked" if meeting.full? %>>
                    </div>
                  <% end %>
                </div>

                <div class="d-flex align-items-center border-top border-light">
                  <div class="col-3 align-self-start d-flex flex-column text-center gap-1 justify-content-center">
                      <div class="date-stamp d-flex flex-column justify-content-center">
                        <p class="day fs-1 fw-bold day"><%= l(meeting.date, format: '%d') %></p>
                        <p class="very-small"><%= l(meeting.date, format: '%B') %></p>
                        <p class="mega-small"><%= l(meeting.date, format: '%a, %kh%M') %></p>
                      </div>
                  </div>

                  <div class="col-9 d-flex flex-column justify-content-between px-4">
                    <div class="d-flex gap-1 flex-column">
                      <div class="players-list">
                        <div class="d-flex align-items-center bg-success-subtle p-1 rounded-2 shadow-sm">
                          <p class="mb-0"><%= meeting.user.username.capitalize %> (Moi)</p>
                        </div>

                        <% meeting.requests.each do |request| %>
                          <% if !request.rejected? %>
                            <div class="d-flex justify-content-between align-items-center p-1 shadow-sm <%= request.status == "interested" ? "bg-danger-subtle rounded-2 mt-2" : "bg-success-subtle" %>">
                              <%= link_to request_path(request) do %>
                                <p class="mb-0">
                                  <%= request.user.username.capitalize %>
                                  <% if request.number_of_friends == 0 %>
                                    seul(e)
                                  <% elsif request.number_of_friends == 1 %>
                                    + 1 ami(e)
                                  <% else %>
                                    + <%= request.number_of_friends %> ami(e)s
                                  <% end %>
                                </p>
                              <% end %>
                              <div>
                                <%= link_to accept_request_path(request), data: { turbo_method: :patch } do %>
                                  <% if request.interested? %>
                                    <i class="fa-regular fa-circle-check px-2"></i>
                                  <% end %>
                                <% end %>
                                <%= link_to reject_request_path(request), data: { turbo_method: :patch, turbo_confirm: "Es-tu certain d'annuler cette demande?" } do %>
                                  <i class="fa-solid fa-xmark"></i>
                                <% end %>
                              </div>
                            </div>
                          <% end %>
                        <% end %>
                      </div>
                      <div class="player-count">
                        <% if compute_players(meeting) > 1 %>
                          <span><%= compute_players(meeting) %> joueurs au compteur 🔥</span>
                        <% else %>
                          <div>
                            <p class="mb-0">Pas d'autre joueur 🫤</p>
                            <p class="location-small text-secondary">Accepte les demandes s'il y en a !</p>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="d-flex pt-2">
                  <%= link_to  meeting_message_path(meeting), class:"flex-fill d-flex mx-1 " do %>
                    <button class="btn btn-primary btn-sm flex-fill activity-button">
                      <i class="fa-regular fa-message"></i>
                      <span class="inner-btn-margin-left">
                        Ecrire au groupe
                      </span>
                    </button>
                  <% end %>
                  <%= link_to cancel_meeting_path(meeting), class:"flex-fill d-flex mx-1" , data: { turbo_method: :patch, turbo_confirm: "Es-tu certain d'annuler cette rencontre?", controller: "cancel-meeting-alert", action: "click->cancel-meeting-alert#alert" } do %>
                    <button id="meeting-<%= meeting.id %>" class="btn btn-danger btn-sm flex-fill activity-button">
                      <i class="fa-solid fa-xmark"></i>
                      <span class="inner-btn-margin-left">Annuler</span>
                    </button>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>


      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionConvo">
        <div class="accordion-body">

            <% @requested_meetings.each do |meeting| %>
            <div class="p-1 mt-4 rounded-5">
              <div class="request-card bg-white text-black px-3 rounded-5 shadow">
                <div class="d-flex justify-content-between mb-2">
                  <div class="text-start">
                    <h4 class="mb-0"><%= link_to meeting.game.name, meeting_path(meeting) %></h4>
                    <p class="location-small text-secondary">
                    <i class="fa-solid fa-location-dot"></i>
                    <% if meeting.place_name.blank? %>
                      Aucun lieu défini
                    <% else %>
                      <%= meeting.place_name %>
                    <% end %>
                    </p>
                  </div>

                  <div class="request-status m-0 d-flex justify-content-end text-end">
                    <div class="<%=meeting.requests.find_by(user_id: current_user).status %>">
                      <%= Request.statuses[meeting.requests.find_by(user_id: current_user).status] %>
                    </div>
                  </div>
                </div>

                  <div class="d-flex align-items-center border-top border-light">
                    <div class="col-3 align-self-start d-flex flex-column text-center gap-1 justify-content-center">
                        <div class="date-stamp d-flex flex-column justify-content-center">
                          <p class="day fs-1 fw-bold day"><%= l(meeting.date, format: '%d') %></p>
                          <p class="very-small"><%= l(meeting.date, format: '%B') %></p>
                          <p class="mega-small"><%= l(meeting.date, format: '%a, %kh%M') %></p>
                        </div>
                    </div>

                  <%= link_to request_path(meeting.requests.find_by(user_id: current_user)) do %>
                    <div class="col-9 d-flex flex-column justify-content-between px-4">
                      <div class="d-flex gap-1 flex-column">
                        <div class="players-list">
                            <div class="d-flex justify-content-between align-items-center p-1 shadow-sm bg-success-subtle">
                              <%= meeting.user.username.capitalize %> (Orga)
                              </div>

                          <% meeting.requests.each do |request| %>
                            <% if request.accepted? %>
                            <div class="d-flex justify-content-between align-items-center p-1 shadow-sm bg-success-subtle">
                              <%= request.user.username.capitalize %> <%= "(Moi)" if request.user == current_user %>
                            </div>
                            <% end %>
                          <% end %>
                        </div>
                          <% end %>

                        <div class="player-count">
                          <% if compute_players(meeting) > 1 %>
                            <span><%= compute_players(meeting) %> joueurs au compteur 🔥</span>
                          <% else %>
                            <div>
                              <p class="mb-0">Pas d'autre joueur 🫤</p>
                              <p class="location-small text-secondary">Accepte les demandes s'il y en a !</p>
                            </div>
                          <% end %>
                        </div>

                      <p class="form-check form-switch p-2 d-flex justify-content-center">
                        <%= Meeting.statuses[meeting.status] if Meeting.statuses[meeting.status] == Meeting.statuses[:full] %>
                      </p>
                    </div>
                  </div>
                  </div>
                <div class="d-flex pt-2">
                  <%= link_to  meeting_message_path(meeting), class:"flex-fill d-flex mx-1 " do %>
                    <button class="btn btn-primary btn-sm flex-fill activity-button">
                      <i class="fa-regular fa-message"></i>
                      <span class="inner-btn-margin-left">
                        Ecrire au groupe
                      </span>
                    </button>
                  <% end %>
                  <%= link_to request_path(meeting.requests.find_by(user_id: current_user)), data: { turbo_method: :delete, turbo_confirm: "Es-tu certain d'annuler ta participation?" } do %>
                    <button class="btn btn-danger btn-sm flex-fill activity-button">
                      <i class="fa-solid fa-xmark"></i>
                      <span class="inner-btn-margin-left">Annuler ma participation</span>
                    </button>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="row col-6 m-auto pt-3 gap-2">
          <%= link_to "Retour", :back, class: "btn btn-secondary" %>
          <%= link_to "Liste des jeux", meetings_path, class: "btn btn-secondary" %>
        </div>
        <%= render "shared/fixed_new_button" %>
      </div>
    </div>
  </div>
  </div>

app/views/requests/show.html.erb
<div class="container">
  <h1 class="text-center pb-3">Détail de la demande de participation</h1>
  <p>Jeu: <%= @request.meeting.game.name %></p>
  <p>Category: <%= @request.meeting.game.category %></p>
  <p>Nombre de joueurs souhaitant rejoindre le jeu: <%= @request.number_of_friends %> ami.e.s + moi</p>
  <%= link_to "Modifier", edit_request_path(@request) %>
  <p>Lieu: <%= @request.meeting.place_name %>, <%= @request.meeting.place_address %></p>
  <p>Status: <%= @request.status %></p>
  <% if @request.meeting.players_needed_max %>
  <p>Nombre de joueurs encore nécessaire avant validation: <%= @request.meeting.players_needed_max - @request.meeting.players_needed_min %></p>
  <% end %>
  <%= link_to "Retour aux demandes", requests_path %>
</div>